name: Daily Website Check

on:
  schedule:
    # Runs at 02:30 UTC (8:00 AM GMT+5:30) and 08:50 UTC (2:20 PM GMT+5:30) every day
    - cron: "30 2 * * *"  # 8:00 AM GMT+5:30
    - cron: "50 8 * * *"  # 2:20 PM GMT+5:30

jobs:
  check_and_email:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"

    # Install dependencies (if any)
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    # Run the Python script from the root directory
    - name: Run the website check script
      run: python hcm.py
