name: Daily Website Check

on:
  #schedule:
   # - cron: "*/30 * * * *"  # Every 30 minutes
  workflow_dispatch:  # Manual triggering

jobs:
  check_and_email:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"

    # Install dependencies (if any)
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    # Run the Python script from the root directory
    - name: Run the website check script
      run: python web_status.py
